version: "3.8"

services:
  frontend:
    container_name: frontend
    build: ./docker/node
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/var/www
    tty: true

  backend:
    container_name: backend
    build: ./docker/php
    ports:
      - ${BACKEND_PORT}:8000
    volumes:
      - ./api:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./log:/var/log

  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db_next_laravel
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  phpmyadmin-database:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-database
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=${PMA_PASSWORD}
    links:
      - database
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - /sessions